# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Shannon Duncan - Software Developer
email: jsduncan98@gmail.com
description: "A full stack software developer, a father, and a gamer. Not much else here..."
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://shadowcodex.github.io" # the base hostname & protocol for your site
twitter_username: iamMrDuncan
github_username:  shadowcodex
seokeyworddefault: "full stack developer"
ogimg: "https://shadowcodex.github.io/imgs/ogimg.jpg"

# Build settings
markdown: kramdown

plugins:
  - jekyll-sitemap
